### ISSUE TITLE
processor.worker.js 这个报错有办法解决吗

### ISSUE THREAD

**Issue by RockLD** [xwhking/xunfei-spark-voice-translate-component#1]
![image](https://github.com/xwhking/xunfei-spark-voice-translate-component/assets/46001500/e4036988-35b1-401d-9de5-5e2327400a90)

也是vite+vue3+js项目，直接把代码复制过去就报这个错误，不知道是哪里冲突还是怎么

**Comment by xwhking** [comment]
应该是找不到依赖，我这个项目运行的依赖依托于 voice-utils 这个目录，并且这个目录需要放在 src 下面，如果想自己修改地方的话可以在voice-translate中进行修改引入地址。如果还不行，请提供更多信息！

**Comment by RockLD** [comment]
> 应该是找不到依赖，我这个项目运行的依赖依托于 voice-utils 这个目录，并且这个目录需要放在 src 下面，如果想自己修改地方的话可以在voice-translate中进行修改引入地址。如果还不行，请提供更多信息！

谢谢，已经找到问题了，我把processor.worker.js 文件改成mjs就好了~~~
